apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-05-30T09:00:00Z"
  generation: 1
  labels:
    app: spring-petclinic-api
  name: spring-petclinic-rest-v2
  namespace: default
  resourceVersion: "3000"
  uid: 8f9ac45e-1234-4c2d-b987-df123456abcd
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: spring-petclinic-api
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic-api
    spec:
      containers:
      - image: docker.io/springcommunity/spring-petclinic-rest:3.0.2
        imagePullPolicy: IfNotPresent
        name: spring-petclinic-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-05-30T09:05:00Z"
    lastUpdateTime: "2025-05-30T09:05:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-30T09:00:00Z"
    lastUpdateTime: "2025-05-30T09:10:00Z"
    message: ReplicaSet "spring-petclinic-rest-v2-7abcde1234" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
