apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T09:15:45Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2134"
  uid: f8c9a7e1-1234-4bd9-a0de-9e00acdef123
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.150.200 # bisa diganti kalau perlu
  clusterIPs:
    - 10.103.150.200
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32328 
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
